import type { Product } from "./types";

// Fallback catalog shown when Supabase isn't reachable yet (missing/invalid
// NEXT_PUBLIC_SUPABASE_URL, no "products" table, offline, etc.) so the UI
// never looks broken during setup. Swap these for real products by adding
// rows in Supabase — this file isn't imported once that data loads fine.
export const MOCK_PRODUCTS: Product[] = [
  {
    id: "mock-1",
    slug: "oversized-reaper-tee",
    title: "Oversized Reaper Tee",
    description: "Heavyweight 240gsm cotton, boxy fit, faded skull back print.",
    price: 1299,
    image_url: "https://picsum.photos/seed/roguestitches-tee-1/600/750",
    category: "t-shirts",
    sizes: ["S", "M", "L", "XL", "XXL"],
    in_stock: true,
    stock: 18,
    is_new: true,
  },
  {
    id: "mock-2",
    slug: "midnight-cargo-pants",
    title: "Midnight Cargo Pants",
    description: "Relaxed straight-leg cargos with triple stitching and side pockets.",
    price: 2799,
    image_url: "https://picsum.photos/seed/roguestitches-cargo-1/600/750",
    category: "bottoms",
    sizes: ["S", "M", "L", "XL"],
    in_stock: true,
    stock: 9,
    is_new: false,
  },
  {
    id: "mock-3",
    slug: "oxblood-zip-hoodie",
    title: "Oxblood Zip Hoodie",
    description: "Brushed fleece interior, oxblood embroidered chest logo.",
    price: 3199,
    image_url: "https://picsum.photos/seed/roguestitches-hoodie-1/600/750",
    category: "hoodies",
    sizes: ["M", "L", "XL", "XXL"],
    in_stock: true,
    stock: 4,
    is_new: true,
  },
  {
    id: "mock-4",
    slug: "distressed-denim-shirt",
    title: "Distressed Denim Shirt",
    description: "Raw-edge overshirt, hand-distressed, woven back patch.",
    price: 3799,
    image_url: "https://picsum.photos/seed/roguestitches-denim-1/600/750",
    category: "shirts",
    sizes: ["S", "M", "L", "XL"],
    in_stock: false,
    stock: 0,
    is_new: false,
  },
  {
    id: "mock-5",
    slug: "blackletter-oversized-tee",
    title: "Blackletter Oversized Tee",
    description: "Gothic blackletter wordmark, garment-dyed for a worn-in look.",
    price: 1399,
    image_url: "https://picsum.photos/seed/roguestitches-tee-2/600/750",
    category: "t-shirts",
    sizes: ["S", "M", "L", "XL", "XXL"],
    in_stock: true,
    stock: 22,
    is_new: true,
  },
  {
    id: "mock-6",
    slug: "rogue-track-pants",
    title: "Rogue Track Pants",
    description: "Tapered fit, side stripe, elastic cuff, everyday streetwear staple.",
    price: 2199,
    image_url: "https://picsum.photos/seed/roguestitches-track-1/600/750",
    category: "bottoms",
    sizes: ["S", "M", "L", "XL"],
    in_stock: true,
    stock: 14,
    is_new: false,
  },
  {
    id: "mock-7",
    slug: "skull-chain-hoodie",
    title: "Skull Chain Hoodie",
    description: "Oversized hood, kangaroo pocket, chain-and-skull graphic print.",
    price: 3399,
    image_url: "https://picsum.photos/seed/roguestitches-hoodie-2/600/750",
    category: "hoodies",
    sizes: ["M", "L", "XL", "XXL"],
    in_stock: true,
    stock: 7,
    is_new: true,
  },
  {
    id: "mock-8",
    slug: "rogue-flannel-shirt",
    title: "Rogue Flannel Shirt",
    description: "Brushed flannel overshirt, snap buttons, embroidered back patch.",
    price: 2299,
    image_url: "https://picsum.photos/seed/roguestitches-bomber-1/600/750",
    category: "shirts",
    sizes: ["S", "M", "L", "XL"],
    in_stock: true,
    stock: 11,
    is_new: false,
  },
];
